# Generated by Django 5.2.14 on 2026-05-27 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('tayyorlanmoqda', 'Tayyorlanmoqda'), ('yolda', "Yo'lda 🚚"), ('yetkazildi', 'Yetkazildi ✅')], default='yangi', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('price', models.CharField(max_length=100, verbose_name='Narxi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasmi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bot_app.category', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Mijoz ismi')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('extra_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name="Qo'shimcha tel")),
                ('order_amount', models.CharField(max_length=100, verbose_name='Xohlagan ulush summasi')),
                ('location', models.CharField(max_length=500, verbose_name='Manzil / Lokatsiya')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kelgan vaqti')),
                ('status', models.CharField(default='yangi', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
