# Generated by Django 5.2.14 on 2026-05-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='Mijoz ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram Username')),
                ('client_name', models.CharField(max_length=255, verbose_name='Mijoz ismi')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('product_name', models.CharField(max_length=255, verbose_name='Sotib olingan mahsulot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma vaqti')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Mahsulot nomi')),
                ('price', models.CharField(max_length=100, verbose_name='Narxi')),
                ('image_id', models.CharField(max_length=255, verbose_name='Telegram Rasm ID')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
    ]
